# Generated by Django 5.0.1 on 2024-01-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='изображение')),
                ('place', models.CharField(max_length=100, verbose_name='место работы')),
            ],
        ),
    ]
