# Generated by Django 5.0.1 on 2024-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('message', models.TextField(max_length=500, verbose_name='сообщение')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
